notifications:
  email: false
language: node_js
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
script:
- npm run build
deploy:
  provider: pages
  fqdn: developers.windingtree.com
  local-dir: _book
  skip-cleanup: true
  github-token: $GH_PAGES_DEPLOY_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
     branch: master
